### ISSUE TITLE
收藏操作失败

### ISSUE THREAD

**Issue by Lvjinhong** [freshgeek/auto-back-fanatical-fans#1]
![image](https://user-images.githubusercontent.com/96970081/180632453-82d35fab-cccb-4d6b-830d-28f439aaeefb.png)

这里为什么会出现用户校验失败呢？

**Comment by freshgeek** [comment]
https://github.com/freshgeek/auto-back-fanatical-fans
![575815c1bee9508fadc8d37954697e8](https://user-images.githubusercontent.com/20513615/180633691-326a6f84-5003-454f-abc0-1095edd06d06.png)
这边配置一下收藏夹id
